name: Continuous Persistent VPS

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  vps-session:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Just under 6 hours

    steps:
  

    

      - name: Install prerequisites
        run: |
          curl -sSf https://sshx.io/get | sh

      - name: Start sshx
        run: |
          sshx &

    
      - name: Sleep to keep VPS alive
        run: sleep 350000000  # 6 hours

    
          
          
